language: python
python:
    - 3.6
install:
    - pip install -r requirements.txt
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6/
  - export CHROME_BIN=chromium-browser

script:
    - python manage.py test
addons:
  chrome: stable
