language: python
python:
    - 3.6
install:
    - pip install -r requirements.txt
addons:
  chrome: stable
before_install:
  - pip install selenium
  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7/lib/python3.6/bin/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - python manage.py test
