# Generated by Django 3.1.dev20200113081333 on 2020-01-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20200125_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='subsExtraId',
            field=models.ManyToManyField(blank=True, related_name='subsExtraID', to='pizza.SubsExtra'),
        ),
    ]
