# Generated by Django 3.1.dev20200113081333 on 2020-02-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_orderdetails_subsextraid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
